spring.application.name=askmom-api-gateway
server.port=${SERVER_PORT:9000}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=${USER_SERVICE_URI:http://localhost:9180}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**,/api/user/**,/api/user-profile/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[1].id=maternal-service
spring.cloud.gateway.server.webflux.routes[1].uri=${MATERNAL_SERVICE_URI:http://localhost:9181}
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/maternal-profile/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.server.webflux.routes[2].id=baby-service
spring.cloud.gateway.server.webflux.routes[2].uri=${BABY_SERVICE_URI:http://localhost:9182}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/baby/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1
